### ISSUE TITLE
Consider adding examples for extras_require

### ISSUE THREAD

**Issue by wimglenn** [navdeep-G/setup.py#39]
Perhaps the project could benefit from adding syntax examples for two useful features, commonly seen in the wild:

- [extras](https://www.python.org/dev/peps/pep-0508/#extras), e.g. `myproj[this,stuff]`
- [conditional deps](https://www.python.org/dev/peps/pep-0508/#environment-markers), i.e. environment markers (e.g., requiring backports only when needed)

Additionally, I think the `UploadCommand` thing is feature bloat and should be removed.  It doesn't really belong here directly in `setup.py`, being duplicated in each and every project.  Maybe just add a comment or a link to a good guide about how to use `twine`?

**Comment by florisla** [comment]
Note: there is now an 'extras' example in the master branch.

**Comment by rspeer** [comment]
I disagree: with so much tooling and documentation out there that predates `twine`, updating the behavior of `setup.py upload` is a good thing to do. You can use `twine` separately, but I'd prefer to at least have upload do the right thing instead of the wrong thing.

Also: I like the fact that `python setup.py sdist upload` is one command, while cleaning out the `dist/` directory, running `python setup.py sdist`, and then uploading the result with `twine` is three.

**Comment by wimglenn** [comment]
@rspeer  The content in `setup.py` should be info specific to that project.  I agree that default behaviour for `python setup.py upload` could be improved, but this needs to be addressed directly in distutils and/or setuptools, not copy-pasted from github.com/kennethreitz.

**Comment by rspeer** [comment]
You're asking for this to be blocked by impossible things, @wimglenn. The behavior of distutils cannot be changed, because it's in the standard library. And making setuptools depend on twine would be a circular dependency.

There has been some very vague discussion of how to improve this situation, but clearly nothing will happen soon. The pypa maintainers already expect people who want to be able to use `setup.py upload` to patch it in their own setup scripts.

**Comment by wimglenn** [comment]
@rspeer  The upload command is now deprecated by setuptools.  See https://setuptools.readthedocs.io/en/latest/history.html and https://github.com/pypa/setuptools/pull/1410

**Comment by wimglenn** [comment]
This entire repository is basically obsoleted by [PEP 517/PEP 518](https://medium.com/@grassfedcode/pep-517-and-518-in-plain-english-47208ca8b7a6).  Closing.
